import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const sourceDirectory = "/Users/simonomi/google drive​/github/obsidian-markdown-pitch-accent/"
const destinationDirectory = "/Users/simonomi/Library/Mobile Documents/iCloud~md~obsidian/Documents/main/.obsidian/plugins/obsidian-markdown-pitch-accent/"
const filesToCopy = [
	"main.js",
	"manifest.json",
	"styles.css"
]

function copyFiles() {
	if (!fs.existsSync(destinationDirectory)){
		fs.mkdirSync(destinationDirectory);
	}
	
	for (const file of filesToCopy) {
		const source = sourceDirectory + file
		const destination = destinationDirectory + file
		fs.copyFile(source, destination, (error) => {
			if (error != null) {
				console.log(error)
			}
		})
	}
}

copyFiles()

const prod = (process.argv[2] === 'production');

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/closebrackets',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/comment',
		'@codemirror/fold',
		'@codemirror/gutter',
		'@codemirror/highlight',
		'@codemirror/history',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/matchbrackets',
		'@codemirror/panel',
		'@codemirror/rangeset',
		'@codemirror/rectangular-selection',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/stream-parser',
		'@codemirror/text',
		'@codemirror/tooltip',
		'@codemirror/view',
		...builtins],
	format: 'cjs',
	watch: !prod,
	watch: {
		onRebuild(error, result) {
			copyFiles()
		},
	},
	target: 'es2016',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
}).catch(() => process.exit(1));
